local opts = {
  attach_mode = "global",
  backends = { "lsp", "treesitter", "markdown", "man" },
  layout = { min_width = 28 },
  filter_kind = false,
  icons = {
    Array = "󱡠",
    Boolean = "󰨙",
    Class = "󰆧",
    Constant = "󰏿",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "󰈙",
    Function = "󰊕",
    Interface = "",
    Key = "󰌋",
    Method = "󰊕",
    Module = "",
    Namespace = "󰦮",
    Null = "󰟢",
    Number = "󰎠",
    Object = "",
    Operator = "󰆕",
    Package = "",
    Property = "",
    String = "",
    Struct = "󰆼",
    TypeParameter = "󰗴",
    Variable = "󰀫",
    Collapsed = "",
  },
  keymaps = {
    ["[y"] = "actions.prev",
    ["]y"] = "actions.next",
    ["[Y"] = "actions.prev_up",
    ["]Y"] = "actions.next_up",
    ["{"] = false,
    ["}"] = false,
    ["[["] = false,
    ["]]"] = false,
  },
}

require("utils.plugin").load {
  name = "aerial",
  opts = opts,
}
