# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bufferline-nvim = {
    pname = "bufferline-nvim";
    version = "73540cb95f8d95aa1af3ed57713c6720c78af915";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "73540cb95f8d95aa1af3ed57713c6720c78af915";
      fetchSubmodules = false;
      sha256 = "sha256-bHlmaNXfZTlTm/8v48FwCde9ljZFLv25efYF5355bnw=";
    };
    date = "2024-04-22";
  };
  gp-nvim = {
    pname = "gp-nvim";
    version = "52938ffbd47b5e06d0f9b7c8b146f26d6021fbac";
    src = fetchFromGitHub {
      owner = "Robitx";
      repo = "gp.nvim";
      rev = "52938ffbd47b5e06d0f9b7c8b146f26d6021fbac";
      fetchSubmodules = false;
      sha256 = "sha256-nowrrgdRxxJ81xsmuUYKsbPNLTGVKO6KbSpU0U98lWE=";
    };
    date = "2024-03-26";
  };
}
