# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  copilot-status-nvim = {
    pname = "copilot-status-nvim";
    version = "ea9e7000e82a89aac9d8434675dfed3da4ec1158";
    src = fetchFromGitHub {
      owner = "ofseed";
      repo = "copilot-status.nvim";
      rev = "ea9e7000e82a89aac9d8434675dfed3da4ec1158";
      fetchSubmodules = false;
      sha256 = "sha256-DR9H8ZDmEidXCyCIzuQTQFpvnPiV0xfUfQC6XOc2RkM=";
    };
    date = "2024-05-29";
  };
  kitty-scrollback-nvim = {
    pname = "kitty-scrollback-nvim";
    version = "3f430ff8829dc2b0f5291d87789320231fdb65a1";
    src = fetchFromGitHub {
      owner = "mikesmithgh";
      repo = "kitty-scrollback.nvim";
      rev = "3f430ff8829dc2b0f5291d87789320231fdb65a1";
      fetchSubmodules = false;
      sha256 = "sha256-6aU9lXfRtxJA/MYkaJ4iRQYAnpBBSGI1R6Ny048aJx8=";
    };
    date = "2024-08-20";
  };
  kulala-nvim = {
    pname = "kulala-nvim";
    version = "a2a8e82fa9172e644804e7a015858ec97f106140";
    src = fetchFromGitHub {
      owner = "mistweaverco";
      repo = "kulala.nvim";
      rev = "a2a8e82fa9172e644804e7a015858ec97f106140";
      fetchSubmodules = false;
      sha256 = "sha256-q+DwDOsk8pN8ayEwh7egtTzAKgN0eGVUtJLtGS0TKoQ=";
    };
    date = "2024-08-20";
  };
  luvit-meta = {
    pname = "luvit-meta";
    version = "ce76f6f6cdc9201523a5875a4471dcfe0186eb60";
    src = fetchFromGitHub {
      owner = "Bilal2453";
      repo = "luvit-meta";
      rev = "ce76f6f6cdc9201523a5875a4471dcfe0186eb60";
      fetchSubmodules = false;
      sha256 = "sha256-zAAptV/oLuLAAsa2zSB/6fxlElk4+jNZd/cPr9oxFig=";
    };
    date = "2024-01-20";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "cbaebd92dce84e9ba63cb07d3199e5a19b204c1a";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "cbaebd92dce84e9ba63cb07d3199e5a19b204c1a";
      fetchSubmodules = false;
      sha256 = "sha256-HnNbB5Nx65Zb5oTjED0et+bAAEVX5+8pZxwTZvxRtQ8=";
    };
    date = "2024-08-02";
  };
  quicker-nvim = {
    pname = "quicker-nvim";
    version = "921a8e5f96dab7fc73b3eca03a98fec6c10270e3";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "quicker.nvim";
      rev = "921a8e5f96dab7fc73b3eca03a98fec6c10270e3";
      fetchSubmodules = false;
      sha256 = "sha256-3mtKKtwBwmA3akJt8NB5Kue9awJ0fxhalrQ07kdCVSA=";
    };
    date = "2024-08-19";
  };
}
