# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  copilot-status-nvim = {
    pname = "copilot-status-nvim";
    version = "ea9e7000e82a89aac9d8434675dfed3da4ec1158";
    src = fetchFromGitHub {
      owner = "ofseed";
      repo = "copilot-status.nvim";
      rev = "ea9e7000e82a89aac9d8434675dfed3da4ec1158";
      fetchSubmodules = false;
      sha256 = "sha256-DR9H8ZDmEidXCyCIzuQTQFpvnPiV0xfUfQC6XOc2RkM=";
    };
    date = "2024-05-29";
  };
  kitty-scrollback-nvim = {
    pname = "kitty-scrollback-nvim";
    version = "d51725a6b71d65dd9df83ddc07903de2fb2736ee";
    src = fetchFromGitHub {
      owner = "mikesmithgh";
      repo = "kitty-scrollback.nvim";
      rev = "d51725a6b71d65dd9df83ddc07903de2fb2736ee";
      fetchSubmodules = false;
      sha256 = "sha256-K2etlw89afHYR791keUF5+BBRybfp2mKaVYWigEXczs=";
    };
    date = "2024-09-27";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "ce43f2eb2a52492157d7742e5f684b9a42bb3e5c";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "ce43f2eb2a52492157d7742e5f684b9a42bb3e5c";
      fetchSubmodules = false;
      sha256 = "sha256-W9jtfVXHC8MQJwdbxakNqhd+xh/auQb3U09XKdN2Wzw=";
    };
    date = "2024-10-09";
  };
  quicker-nvim = {
    pname = "quicker-nvim";
    version = "46e0ad6c6a1d998a294e13cbb8b7c398e140983a";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "quicker.nvim";
      rev = "46e0ad6c6a1d998a294e13cbb8b7c398e140983a";
      fetchSubmodules = false;
      sha256 = "sha256-rlKI23VZ8TzGRvl7C6wu83VpSdkzdHliElUZD+8U0iE=";
    };
    date = "2024-10-15";
  };
}
