vim.opt.breakindent = true
vim.opt.clipboard = vim.env.SSH_CONNECTION and "" or "unnamedplus"
vim.opt.colorcolumn = "80"
vim.opt.completeopt = { "menu", "menuone", "noinsert" }
vim.opt.confirm = true
vim.opt.cursorline = true
vim.opt.expandtab = true
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.opt.foldtext = ""
vim.opt.foldcolumn = "1"
vim.opt.foldlevel = 99
vim.opt.ignorecase = true
vim.opt.jumpoptions = "stack"
vim.opt.linebreak = true
vim.opt.mouse = ""
vim.opt.number = true
vim.opt.numberwidth = 2
vim.opt.pumheight = 10
vim.opt.relativenumber = true
vim.opt.scrolloff = 8
vim.opt.sessionoptions:append("localoptions")
vim.opt.shiftwidth = 0
vim.opt.shortmess:append("I")
vim.opt.showmode = false
vim.opt.showtabline = 2
vim.opt.sidescrolloff = 5
vim.opt.signcolumn = "yes"

vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.smoothscroll = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.tabstop = 2
vim.opt.termguicolors = true
vim.opt.timeoutlen = 300
vim.opt.title = true
vim.opt.undofile = true
vim.opt.updatetime = 300
vim.opt.virtualedit = "block"
vim.opt.wrap = false
