name: Docker
on:
  push:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: [latest, 24.04, 22.04]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_version }}
          tags: cnteng/rx-nvim:${{ matrix.ubuntu_version }}
          file: "docker/Dockerfile"
