name: Auto-merge
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Automerge
        if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
        run: gh pr merge --auto --squash ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
